language: java

jdk:
  - oraclejdk8
  - openjdk11

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global: {} # TODO

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
